// No importes iconos acá. Solo metadata liviana.
export const TECH_STACKS = [
  { id: "adobe", label: "Adobe", iconName: "AdobeIcon" },
  { id: "adobefirefly", label: "Adobe Firefly", iconName: "AdobeFireflyIcon" },
  { id: "ae", label: "After Effects", iconName: "AeIcon" },
  { id: "affinity", label: "Affinity", iconName: "AffinityIcon" },
  {
    id: "affinitydesigner",
    label: "Affinity Designer",
    iconName: "AffinityDesignerIcon",
  },
  {
    id: "affinityphoto",
    label: "Affinity Photo",
    iconName: "AffinityPhotoIcon",
  },
  {
    id: "affinitypublisher",
    label: "Affinity Publisher",
    iconName: "AffinityPublisherIcon",
  },
  { id: "ai", label: "Adobe Illustrator", iconName: "AiIcon" },
  { id: "ai360", label: "AI 360", iconName: "Ai360Icon" },
  { id: "aihubmix", label: "AI Hub Mix", iconName: "AihubmixIcon" },
  { id: "aimass", label: "AI Mass", iconName: "AimassIcon" },
  { id: "aionlabs", label: "Aion Labs", iconName: "AionlabsIcon" },
  { id: "airtable", label: "Airtable", iconName: "AirtableIcon" },
  { id: "aistudio", label: "AI Studio", iconName: "AistudioIcon" },
  { id: "alacritty", label: "Alacritty", iconName: "AlacrittyIcon" },
  { id: "algolia", label: "Algolia", iconName: "AlgoliaIcon" },
  { id: "algorand", label: "Algorand", iconName: "AlgorandIcon" },
  { id: "alibabacloud", label: "Alibaba Cloud", iconName: "AlibabacloudIcon" },
  { id: "alpinejs", label: "Alpine.js", iconName: "AlpinejsIcon" },
  { id: "amp", label: "AMP", iconName: "AmpIcon" },
  {
    id: "amznwebserv",
    label: "Amazon Web Services",
    iconName: "AmznwebservIcon",
  },
  { id: "analytics", label: "Analytics", iconName: "AnalyticsIcon" },
  { id: "android", label: "Android", iconName: "AndroidIcon" },
  { id: "angular", label: "Angular", iconName: "AngularIcon" },
  { id: "angular17", label: "Angular 17", iconName: "Angular17Icon" },
  { id: "animaapp", label: "Anima App", iconName: "AnimaappIcon" },
  { id: "antd", label: "Ant Design", iconName: "AntdIcon" },
  { id: "antgroup", label: "Ant Group", iconName: "AntgroupIcon" },
  { id: "anthropic", label: "Anthropic", iconName: "AnthropicIcon" },
  { id: "anyscale", label: "Anyscale", iconName: "AnyscaleIcon" },
  { id: "apache", label: "Apache", iconName: "ApacheIcon" },
  { id: "appwrite", label: "Appwrite", iconName: "AppwriteIcon" },
  { id: "arc", label: "Arc", iconName: "ArcIcon" },
  { id: "assemblyai", label: "AssemblyAI", iconName: "AssemblyaiIcon" },
  { id: "astro", label: "Astro", iconName: "AstroIcon" },
  { id: "atlassian", label: "Atlassian", iconName: "AtlassianIcon" },
  { id: "atom", label: "Atom", iconName: "AtomIcon" },
  { id: "augment", label: "Augment", iconName: "AugmentIcon" },
  { id: "auth0", label: "Auth0", iconName: "Auth0Icon" },
  { id: "automatic", label: "Automatic", iconName: "AutomaticIcon" },
  { id: "avajs", label: "AVA.js", iconName: "AvajsIcon" },
  { id: "aws", label: "AWS", iconName: "AwsIcon" },
  { id: "axiom", label: "Axiom", iconName: "AxiomIcon" },
  { id: "axm", label: "Axum", iconName: "AxmIcon" },
  { id: "axure", label: "Axure", iconName: "AxureIcon" },
  { id: "aya", label: "Aya", iconName: "AyaIcon" },
  { id: "azure", label: "Azure", iconName: "AzureIcon" },
  { id: "azureai", label: "Azure AI", iconName: "AzureaiIcon" },
  { id: "babel", label: "Babel", iconName: "BabelIcon" },
  { id: "backbonejs", label: "Backbone.js", iconName: "BackbonejsIcon" },
  { id: "baichuan", label: "Baichuan", iconName: "BaichuanIcon" },
  { id: "baidu", label: "Baidu", iconName: "BaiduIcon" },
  { id: "baiducloud", label: "Baidu Cloud", iconName: "BaiducloudIcon" },
  { id: "bash", label: "Bash", iconName: "BashIcon" },
  { id: "bedrock", label: "Bedrock", iconName: "BedrockIcon" },
  { id: "bing", label: "Bing", iconName: "BingIcon" },
  { id: "bitbucket", label: "Bitbucket", iconName: "BitbucketIcon" },
  { id: "bitnami", label: "Bitnami", iconName: "BitnamiIcon" },
  { id: "blueprintjs", label: "Blueprint.js", iconName: "BlueprintjsIcon" },
  { id: "bolt", label: "Bolt", iconName: "BoltIcon" },
  { id: "bootstrap5", label: "Bootstrap", iconName: "Bootstrap5Icon" },
  { id: "brave", label: "Brave", iconName: "BraveIcon" },
  { id: "bulmaui", label: "Bulma UI", iconName: "BulmauiIcon" },
  { id: "bunjs", label: "Bun.js", iconName: "BunjsIcon" },
  { id: "bytedance", label: "ByteDance", iconName: "BytedanceIcon" },
  { id: "c#", label: "C#", iconName: "CsharpIcon" },
  { id: "c++", label: "C++", iconName: "CplusplusIcon" },
  { id: "cakephp", label: "CakePHP", iconName: "CakephpIcon" },
  { id: "canva", label: "Canva", iconName: "CanvaIcon" },
  { id: "cassandradb", label: "Cassandra DB", iconName: "CassandradbIcon" },
  { id: "centml", label: "CentML", iconName: "CentmlIcon" },
  { id: "cerebras", label: "Cerebras", iconName: "CerebrasIcon" },
  { id: "chakraui", label: "Chakra UI", iconName: "ChakrauiIcon" },
  { id: "chatglm", label: "ChatGLM", iconName: "ChatglmIcon" },
  { id: "chrome", label: "Chrome", iconName: "ChromeIcon" },
  { id: "chromium", label: "Chromium", iconName: "ChromiumIcon" },
  { id: "circleci", label: "CircleCI", iconName: "CircleciIcon" },
  { id: "civitai", label: "Civitai", iconName: "CivitaiIcon" },
  { id: "claude", label: "Claude", iconName: "ClaudeIcon" },
  { id: "clickhouse", label: "ClickHouse", iconName: "ClickhouseIcon" },
  { id: "cline", label: "Cline", iconName: "ClineIcon" },
  { id: "clojure", label: "Clojure", iconName: "ClojureIcon" },
  { id: "cloudflare", label: "Cloudflare", iconName: "CloudflareIcon" },
  { id: "cloudinary", label: "Cloudinary", iconName: "CloudinaryIcon" },
  { id: "codefresh", label: "Codefresh", iconName: "CodefreshIcon" },
  { id: "codegeex", label: "CodeGeeX", iconName: "CodegeexIcon" },
  { id: "codeigniter", label: "CodeIgniter", iconName: "CodeigniterIcon" },
  { id: "cogvideo", label: "CogVideo", iconName: "CogvideoIcon" },
  { id: "cogview", label: "CogView", iconName: "CogviewIcon" },
  { id: "cohere", label: "Cohere", iconName: "CohereIcon" },
  { id: "colab", label: "Colab", iconName: "ColabIcon" },
  { id: "comfyui", label: "ComfyUI", iconName: "ComfyuiIcon" },
  { id: "commanda", label: "Commanda", iconName: "CommandaIcon" },
  { id: "copilotms", label: "Microsoft Copilot", iconName: "CopilotmsIcon" },
  { id: "crusoe", label: "Crusoe", iconName: "CrusoeIcon" },
  { id: "csharp", label: "C#", iconName: "CsharpIcon" },
  { id: "css3", label: "CSS", iconName: "Css3Icon" },
  { id: "cypress", label: "Cypress", iconName: "CypressIcon" },
  { id: "dart", label: "Dart", iconName: "DartIcon" },
  { id: "datadog", label: "Datadog", iconName: "DatadogIcon" },
  { id: "dbrx", label: "DB-RX", iconName: "DbrxIcon" },
  { id: "deepinfra", label: "Deepinfra", iconName: "DeepinfraIcon" },
  { id: "deepmind", label: "DeepMind", iconName: "DeepmindIcon" },
  { id: "deno", label: "Deno", iconName: "DenoIcon" },
  { id: "django", label: "Django", iconName: "DjangoIcon" },
  { id: "dlang", label: "Dlang", iconName: "DlangIcon" },
  { id: "doc2x", label: "Doc2X", iconName: "Doc2xIcon" },
  { id: "docker", label: "Docker", iconName: "DockerIcon" },
  { id: "docsearch", label: "DocSearch", iconName: "DocsearchIcon" },
  { id: "docusaurus", label: "Docusaurus", iconName: "DocusaurusIcon" },
  { id: "doubao", label: "Doubao", iconName: "DoubaoIcon" },
  { id: "dovetail", label: "Dovetail", iconName: "DovetailIcon" },
  { id: "ec2", label: "EC2", iconName: "Ec2Icon" },
  { id: "elastic", label: "Elastic", iconName: "ElasticIcon" },
  { id: "electron", label: "Electron", iconName: "ElectronIcon" },
  { id: "elementui", label: "Element UI", iconName: "ElementuiIcon" },
  { id: "elixir", label: "Elixir", iconName: "ElixirIcon" },
  { id: "ember", label: "Ember", iconName: "EmberIcon" },
  { id: "erlang", label: "Erlang", iconName: "ErlangIcon" },
  { id: "esbuild", label: "ESBuild", iconName: "EsbuildIcon" },
  { id: "eslint", label: "ESLint", iconName: "EslintIcon" },
  { id: "exa", label: "Exa", iconName: "ExaIcon" },
  { id: "expressjs", label: "Express.js", iconName: "ExpressjsIcon" },
  { id: "fastgpt", label: "FastGPT", iconName: "FastgptIcon" },
  { id: "faunadb", label: "FaunaDB", iconName: "FaunadbIcon" },
  { id: "featherless", label: "Featherless", iconName: "FeatherlessIcon" },
  { id: "figma", label: "Figma", iconName: "FigmaIcon" },
  { id: "firebase", label: "Firebase", iconName: "FirebaseIcon" },
  { id: "firefox", label: "Firefox", iconName: "FirefoxIcon" },
  { id: "fireworks", label: "Fireworks", iconName: "FireworksIcon" },
  { id: "flask", label: "Flask", iconName: "FlaskIcon" },
  { id: "flutter", label: "Flutter", iconName: "FlutterIcon" },
  { id: "flutterflow", label: "FlutterFlow", iconName: "FlutterflowIcon" },
  { id: "flyio", label: "Fly.io", iconName: "FlyioIcon" },
  { id: "framer", label: "Framer", iconName: "FramerIcon" },
  { id: "gatsby", label: "Gatsby", iconName: "GatsbyIcon" },
  { id: "gcloud", label: "Google Cloud", iconName: "GcloudIcon" },
  { id: "gemini", label: "Gemini", iconName: "GeminiIcon" },
  { id: "gemma", label: "Gemma", iconName: "GemmaIcon" },
  { id: "git", label: "Git", iconName: "GitIcon" },
  { id: "github", label: "GitHub", iconName: "GithubIcon" },
  { id: "gitlab", label: "GitLab", iconName: "GitlabIcon" },
  { id: "go", label: "Go", iconName: "GoIcon" },
  { id: "gradio", label: "Gradio", iconName: "GradioIcon" },
  { id: "grafana", label: "Grafana", iconName: "GrafanaIcon" },
  { id: "grafbase", label: "Grafbase", iconName: "GrafbaseIcon" },
  { id: "graphite", label: "Graphite", iconName: "GraphiteIcon" },
  { id: "graphql", label: "GraphQL", iconName: "GraphqlIcon" },
  { id: "greptile", label: "Greptile", iconName: "GreptileIcon" },
  { id: "gridsome", label: "Gridsome", iconName: "GridsomeIcon" },
  { id: "gruntjs", label: "Grunt.js", iconName: "GruntjsIcon" },
  { id: "gsap", label: "GSAP", iconName: "GsapIcon" },
  { id: "gulp", label: "Gulp", iconName: "GulpIcon" },
  { id: "hailuo", label: "Hailuo", iconName: "HailuoIcon" },
  { id: "haskell", label: "Haskell", iconName: "HaskellIcon" },
  { id: "heroku", label: "Heroku", iconName: "HerokuIcon" },
  { id: "hexo", label: "Hexo", iconName: "HexoIcon" },
  { id: "higress", label: "Higress", iconName: "HigressIcon" },
  { id: "homebrew", label: "Homebrew", iconName: "HomebrewIcon" },
  { id: "hotjar", label: "Hotjar", iconName: "HotjarIcon" },
  { id: "html5", label: "HTML", iconName: "Html5Icon" },
  { id: "huggingface", label: "Hugging Face", iconName: "HuggingfaceIcon" },
  { id: "hunyuan", label: "Hunyuan", iconName: "HunyuanIcon" },
  { id: "hyper", label: "Hyper", iconName: "HyperIcon" },
  { id: "hyper2", label: "Hyper 2", iconName: "Hyper2Icon" },
  { id: "hyperbolic", label: "Hyperbolic", iconName: "HyperbolicIcon" },
  { id: "i18next", label: "i18next", iconName: "I18nextIcon" },
  { id: "iflytekcloud", label: "iFlytek Cloud", iconName: "IflytekcloudIcon" },
  { id: "infermatic", label: "Infermatic", iconName: "InfermaticIcon" },
  { id: "infinigence", label: "Infinigence", iconName: "InfinigenceIcon" },
  { id: "inkspace", label: "Inkspace", iconName: "InkspaceIcon" },
  { id: "insomnia", label: "Insomnia", iconName: "InsomniaIcon" },
  { id: "internlm", label: "InternLM", iconName: "InternlmIcon" },
  { id: "ionic", label: "Ionic", iconName: "IonicIcon" },
  { id: "jamstack", label: "JAMstack", iconName: "JamstackIcon" },
  { id: "java", label: "Java", iconName: "JavaIcon" },
  { id: "jest", label: "Jest", iconName: "JestIcon" },
  { id: "jimeng", label: "Jimeng", iconName: "JimengIcon" },
  { id: "jina", label: "Jina", iconName: "JinaIcon" },
  { id: "jquery", label: "jQuery", iconName: "JqueryIcon" },
  { id: "js", label: "JavaScript", iconName: "JsIcon" },
  { id: "jslint", label: "JSLint", iconName: "JslintIcon" },
  { id: "json", label: "JSON", iconName: "JsonIcon" },
  { id: "kibana", label: "Kibana", iconName: "KibanaIcon" },
  { id: "kimi", label: "Kimi", iconName: "KimiIcon" },
  { id: "kling", label: "Kling", iconName: "KlingIcon" },
  { id: "kluster", label: "Kluster", iconName: "KlusterIcon" },
  { id: "kotlin", label: "Kotlin", iconName: "KotlinIcon" },
  { id: "kubernetes", label: "Kubernetes", iconName: "KubernetesIcon" },
  { id: "langchain", label: "LangChain", iconName: "LangchainIcon" },
  { id: "langfuse", label: "Langfuse", iconName: "LangfuseIcon" },
  { id: "langgraph", label: "LangGraph", iconName: "LanggraphIcon" },
  { id: "langsmith", label: "LangSmith", iconName: "LangsmithIcon" },
  { id: "laravel", label: "Laravel", iconName: "LaravelIcon" },
  { id: "leptonai", label: "Lepton AI", iconName: "LeptonaiIcon" },
  { id: "less", label: "Less", iconName: "LessIcon" },
  { id: "lightroom", label: "Lightroom", iconName: "LightroomIcon" },
  { id: "lit", label: "Lit", iconName: "LitIcon" },
  { id: "liveblocks", label: "Liveblocks", iconName: "LiveblocksIcon" },
  { id: "livekit", label: "LiveKit", iconName: "LivekitIcon" },
  { id: "llamaindex", label: "LlamaIndex", iconName: "LlamaindexIcon" },
  { id: "llava", label: "Llava", iconName: "LlavaIcon" },
  { id: "logrocket", label: "LogRocket", iconName: "LogrocketIcon" },
  { id: "lokalise", label: "Lokalise", iconName: "LokaliseIcon" },
  { id: "lovable", label: "Lovable", iconName: "LovableIcon" },
  { id: "lua", label: "Lua", iconName: "LuaIcon" },
  { id: "luma", label: "Luma", iconName: "LumaIcon" },
  { id: "lunacy", label: "Lunacy", iconName: "LunacyIcon" },
  { id: "make", label: "Make", iconName: "MakeIcon" },
  { id: "mariadb", label: "MariaDB", iconName: "MariadbIcon" },
  { id: "marionette", label: "Marionette", iconName: "MarionetteIcon" },
  { id: "markdown", label: "Markdown", iconName: "MarkdownIcon" },
  { id: "materialui", label: "Material UI", iconName: "MaterialuiIcon" },
  { id: "meta", label: "Meta", iconName: "MetaIcon" },
  { id: "miro", label: "Miro", iconName: "MiroIcon" },
  { id: "mistral", label: "Mistral", iconName: "MistralIcon" },
  { id: "mochajs", label: "Mocha.js", iconName: "MochajsIcon" },
  { id: "modelscope", label: "ModelScope", iconName: "ModelscopeIcon" },
  { id: "mongodb", label: "MongoDB", iconName: "MongodbIcon" },
  { id: "mongoose", label: "Mongoose", iconName: "MongooseIcon" },
  { id: "myshell", label: "MyShell", iconName: "MyshellIcon" },
  { id: "mysql", label: "MySQL", iconName: "MysqlIcon" },
  { id: "n8n", label: "N8N", iconName: "N8nIcon" },
  { id: "neovim", label: "Neovim", iconName: "NeovimIcon" },
  { id: "nestjs", label: "NestJS", iconName: "NestjsIcon" },
  { id: "net", label: "NET", iconName: "NetIcon" },
  { id: "netcore", label: "NET Core", iconName: "NetcoreIcon" },
  { id: "netlify", label: "Netlify", iconName: "NetlifyIcon" },
  { id: "nextjs", label: "Next.js", iconName: "NextjsIcon" },
  { id: "nextjs2", label: "Next.js 2", iconName: "Nextjs2Icon" },
  { id: "nim", label: "Nim", iconName: "NimIcon" },
  { id: "nitro", label: "Nitro", iconName: "NitroIcon" },
  { id: "nodejs", label: "Node.js", iconName: "NodejsIcon" },
  { id: "nova", label: "Nova", iconName: "NovaIcon" },
  { id: "novita", label: "Novita", iconName: "NovitaIcon" },
  { id: "nplcloud", label: "NPL Cloud", iconName: "NplcloudIcon" },
  { id: "npm", label: "NPM", iconName: "NpmIcon" },
  { id: "npm2", label: "NPM 2", iconName: "Npm2Icon" },
  { id: "nuxtjs", label: "Nuxt.js", iconName: "NuxtjsIcon" },
  { id: "nvidia", label: "Nvidia", iconName: "NvidiaIcon" },
  { id: "ocaml", label: "OCaml", iconName: "OcamlIcon" },
  { id: "onedrive", label: "OneDrive", iconName: "OnedriveIcon" },
  { id: "openai", label: "OpenAI", iconName: "OpenaiIcon" },
  { id: "openchat", label: "OpenChat", iconName: "OpenchatIcon" },
  { id: "oracle", label: "Oracle", iconName: "OracleIcon" },
  { id: "pandacss", label: "Panda CSS", iconName: "PandacssIcon" },
  { id: "perplexity", label: "Perplexity", iconName: "PerplexityIcon" },
  { id: "phidata", label: "Phi Data", iconName: "PhidataIcon" },
  { id: "php", label: "PHP", iconName: "PhpIcon" },
  { id: "pinia", label: "Pinia", iconName: "PiniaIcon" },
  { id: "pixijs", label: "Pixi.js", iconName: "PixijsIcon" },
  { id: "pixverse", label: "Pixverse", iconName: "PixverseIcon" },
  { id: "playwright", label: "Playwright", iconName: "PlaywrightIcon" },
  { id: "postgresql", label: "PostgreSQL", iconName: "PostgresqlIcon" },
  { id: "powershell", label: "PowerShell", iconName: "PowershellIcon" },
  { id: "ppio", label: "Ppio", iconName: "PpioIcon" },
  { id: "preact", label: "Preact", iconName: "PreactIcon" },
  { id: "prisma", label: "Prisma", iconName: "PrismaIcon" },
  { id: "ps", label: "Photoshop", iconName: "PsIcon" },
  { id: "pugjs", label: "Pug.js", iconName: "PugjsIcon" },
  { id: "pydanticai", label: "Pydantic AI", iconName: "PydanticaiIcon" },
  { id: "python", label: "Python", iconName: "PythonIcon" },
  { id: "pytorch", label: "PyTorch", iconName: "PytorchIcon" },
  { id: "pytorch3d", label: "PyTorch3D", iconName: "Pytorch3dIcon" },
  { id: "qingyan", label: "Qingyan", iconName: "QingyanIcon" },
  { id: "qiniu", label: "Qiniu", iconName: "QiniuIcon" },
  { id: "qwen", label: "Qwen", iconName: "QwenIcon" },
  { id: "qwik", label: "Qwik", iconName: "QwikIcon" },
  { id: "radixui", label: "Radix UI", iconName: "RadixuiIcon" },
  { id: "rails", label: "Rails", iconName: "RailsIcon" },
  { id: "railway", label: "Railway", iconName: "RailwayIcon" },
  { id: "react", label: "React", iconName: "ReactIcon" },
  { id: "reactquery", label: "React Query", iconName: "ReactqueryIcon" },
  { id: "reactrouter", label: "React Router", iconName: "ReactrouterIcon" },
  { id: "redis", label: "Redis", iconName: "RedisIcon" },
  { id: "redux", label: "Redux", iconName: "ReduxIcon" },
  { id: "reduxsaga", label: "Redux-Saga", iconName: "ReduxsagaIcon" },
  { id: "remix", label: "Remix", iconName: "RemixIcon" },
  { id: "render", label: "Render", iconName: "RenderIcon" },
  { id: "replit", label: "Replit", iconName: "ReplitIcon" },
  { id: "resend", label: "Resend", iconName: "ResendIcon" },
  { id: "rollup", label: "Rollup", iconName: "RollupIcon" },
  { id: "roocode", label: "Roo Code", iconName: "RoocodeIcon" },
  { id: "rsshub", label: "RSSHub", iconName: "RsshubIcon" },
  { id: "ruby", label: "Ruby", iconName: "RubyIcon" },
  { id: "rust", label: "Rust", iconName: "RustIcon" },
  { id: "sambanova", label: "SambaNova", iconName: "SambanovaIcon" },
  { id: "sass", label: "Sass", iconName: "SassIcon" },
  { id: "scala", label: "Scala", iconName: "ScalaIcon" },
  { id: "search1api", label: "Search1API", iconName: "Search1apiIcon" },
  { id: "semanticui", label: "Semantic UI", iconName: "SemanticuiIcon" },
  { id: "sensenova", label: "SenseNova", iconName: "SensenovaIcon" },
  { id: "serverless", label: "Serverless", iconName: "ServerlessIcon" },
  { id: "shadcnui", label: "Shadcn UI", iconName: "ShadcnuiIcon" },
  { id: "siliconcloud", label: "Silicon Cloud", iconName: "SiliconcloudIcon" },
  { id: "sketch", label: "Sketch", iconName: "SketchIcon" },
  { id: "sketch2", label: "Sketch 2", iconName: "Sketch2Icon" },
  { id: "snowflake", label: "Snowflake", iconName: "SnowflakeIcon" },
  { id: "solidity", label: "Solidity", iconName: "SolidityIcon" },
  { id: "solidjs", label: "Solid.js", iconName: "SolidjsIcon" },
  { id: "spark", label: "Spark", iconName: "SparkIcon" },
  { id: "spring", label: "Spring", iconName: "SpringIcon" },
  { id: "stability", label: "Stability", iconName: "StabilityIcon" },
  { id: "statecloud", label: "State Cloud", iconName: "StatecloudIcon" },
  { id: "stepfun", label: "StepFun", iconName: "StepfunIcon" },
  { id: "storyblok", label: "Storyblok", iconName: "StoryblokIcon" },
  { id: "storybook", label: "Storybook", iconName: "StorybookIcon" },
  { id: "strada", label: "Strada", iconName: "StradaIcon" },
  { id: "stream", label: "Stream", iconName: "StreamIcon" },
  { id: "streamlit", label: "Streamlit", iconName: "StreamlitIcon" },
  { id: "supabase", label: "Supabase", iconName: "SupabaseIcon" },
  { id: "sveltejs", label: "Svelte.js", iconName: "SveltejsIcon" },
  { id: "swagger", label: "Swagger", iconName: "SwaggerIcon" },
  { id: "swift", label: "Swift", iconName: "SwiftIcon" },
  { id: "tailwindcss", label: "Tailwind CSS", iconName: "TailwindcssIcon" },
  { id: "targon", label: "Targon", iconName: "TargonIcon" },
  { id: "tencent", label: "Tencent", iconName: "TencentIcon" },
  { id: "tencentcloud", label: "Tencent Cloud", iconName: "TencentcloudIcon" },
  { id: "typescript", label: "Typescript", iconName: "Typescript" },
  { id: "threejs", label: "Three.js", iconName: "ThreejsIcon" },
  { id: "ubuntu", label: "Ubuntu", iconName: "UbuntuIcon" },
  { id: "udio", label: "Udio", iconName: "UdioIcon" },
  { id: "unjs", label: "UnJS", iconName: "UnjsIcon" },
  { id: "unstructured", label: "Unstructured", iconName: "UnstructuredIcon" },
  { id: "upstage", label: "Upstage", iconName: "UpstageIcon" },
  { id: "vercel", label: "Vercel", iconName: "VercelIcon" },
  { id: "vertexai", label: "Vertex AI", iconName: "VertexaiIcon" },
  { id: "vidu", label: "Vidu", iconName: "ViduIcon" },
  { id: "vim", label: "Vim", iconName: "VimIcon" },
  { id: "visualbasic", label: "Visual Basic", iconName: "VisualbasicIcon" },
  { id: "vitejs", label: "Vite.js", iconName: "VitejsIcon" },
  { id: "vitest", label: "Vitest", iconName: "VitestIcon" },
  { id: "vllm", label: "VLLM", iconName: "VllmIcon" },
  { id: "volcengine", label: "Volcengine", iconName: "VolcengineIcon" },
  { id: "voyage", label: "Voyage", iconName: "VoyageIcon" },
  { id: "vuejs", label: "Vue.js", iconName: "VuejsIcon" },
  { id: "webassembly", label: "WebAssembly", iconName: "WebassemblyIcon" },
  { id: "webpack", label: "Webpack", iconName: "WebpackIcon" },
  { id: "wenxin", label: "Wenxin", iconName: "WenxinIcon" },
  { id: "wordpress", label: "WordPress", iconName: "WordpressIcon" },
  { id: "workersai", label: "Workers AI", iconName: "WorkersaiIcon" },
  { id: "xamarin", label: "Xamarin", iconName: "XamarinIcon" },
  { id: "xd", label: "XD", iconName: "XdIcon" },
  { id: "xinference", label: "Xinference", iconName: "XinferenceIcon" },
  { id: "yi", label: "Yi", iconName: "YiIcon" },
  { id: "yoga", label: "Yoga", iconName: "YogaIcon" },
  { id: "zapier", label: "Zapier", iconName: "ZapierIcon" },
];
